--- 
title: "Introduction to Management Strategy Evaluation"
author: "Gavin Fay"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This is a ASMFC training workshop held remotely during August 2021"
---

# Welcome {#welcome}

_Introduction to Management Strategy Evaluation to support strategic decision-making for fisheries management_: Hello! This is a course taught by Dr. Gavin Fay for the Atlantic States Marine Fisheries Commission: August 16-20, 2021. 

__Description__: This training workshop provides fisheries scientists with instruction and hands-on practical modeling experience in an introduction to Management Strategy Evaluation (MSE), for applications to ASMFC (jointly-)managed stocks and participation in MSE technical Committees. MSE is well-recognized approach for strategic decision-making in fisheries management, providing methods to compare among policy options and assess their robustness in meeting a range of management objectives.

The objectives of the workshop are to: 1) Provide an overview of the MSE process and components of an MSE, and 2) demonstrate through applied examples and modeling exercises on the components of closed loop simulation analyses that form the basis of the analytical aspects of an MSE. 
Modeling exercises and case studies will emphasize different aspects and features of MSEs, and a range of examples will emulate features of the stock dynamics and fisheries managed and jointly managed by the ASMFC (possible examples are American lobster, striped bass, summer flounder, menhaden and herring).

The workshop will consist of synchronous webinar sessions, with active learning opportunities through discussions and in-class modeling exercises, and additional homework to further develop the case studies explored.
The primary focus of the workshop will be on the technical analysis components of MSEs and the interpretation and visualization of results, but the role of stakeholder engagement in MSE processes for co-developing objectives, policy alternatives, and performance metrics will also be overviewed.

This website (built in R!) provides access to the workshop materials and will be updated during the workshop as we progress (and adapt).

**This website**: <https://gavinfay.github.io/asmfc-mse/>  
**GitHub repo**: <https://github.com/rstudio-conf-2020/r-for-excel>  
<!-- **Accompanying slides**: [Google Slides]()-->

---

**About the instructor**

[Gavin Fay](https://thefaylab.com) is an Associate Professor of Fisheries Oceanography at the University of Massachusetts Dartmouth's School for Marine Science and Technology, based in New Bedford, MA.
[Email](mailto:gfay@umassd.edu)
[Twitter](https://twitter.com/gavin_fay)

---

## Agenda {.unnumbered}
_(subject to change)_

<!-- |8/16 |  [Overview](#overview), [R & RStudio, RMarkdown](#rstudio) (JL) |  [Tidying](#tidying) (AH) | -->
<!-- |break      |  | | -->
<!-- |11-12:30   | [Intro to GitHub](#github) (JL) | [Filters & joins](#filter-join) (AH) | -->
<!-- |lunch      |  || -->
<!-- |13:30-15:00 | [Graphs with `ggplot2`](#ggplot2) (AH) | [Collaborating & getting help](#collaborating) (JL) | -->
<!-- |break      |  | | -->
<!-- |15:30-17:00 | [Pivot Tables & `dplyr`](#pivot-tables) (JL) | [Synthesis](#synthesis) (AH) | -->

|Day|Time|Topic|
|:--|:----|:---------|
| M | 1-2:30  | [What is MSE? (lecture & MSE game)](#intro) |
| M | 3-5 |  [My first MSE (R: intro exercise)](#first-mse) |
| T | 9-10  | [designing operating models (lecture)](#op-mods) |
| T | 10:30-12 | [coding & implementing OMs (R lab breakouts, discussion)](#coding-oms) |
| T | 1-2:30 | [selecting management strategies (lecture, R: comparing HCRs)](#management-strategies) |
| T | 3-5 | [Objectives & Performance metrics (lecture, R lab)](#objectives) |
| W | 9-9:15 | Reading discussion |
| W | 9:15 -10:15 | [Code-through of day 2 exercise](#objectives) |
| W | 10:30-11:30 | [Objectives & Performance metrics (lecture)](#objectives) |
| W | 11:30-12:00 | [Stakeholder engagement (discussion)](#stakeholders) |
| W | 1-2 | [Case studies: developing objectives & candidate strategies for ASMFC examples (breakout exercise)](#case-studies) |
| W | 2-2:45 | [Case study review. Relevant OM & HCR needs.](#project-needs) |
| W | 3-4 | breakout group coding on case study projects |
| W | 4-5 | [Presenting results to managers (lecture)](#communication) |
| Th | 9-10 | OM and EMs revisited (lecture, live code) |
| Th | 10:30-12 | Implementation error (lecture, R exercise) |
| Th | 1-2:30 | Case study project work time |
| Th | 3-5 | [multispecies MSEs (lecture, R exercise)](#ecosystem-mse) |
| F | 9-10 | [Coupled system MSEs](#system-mse) |
| F | 10:30-12 | Case study project summaries, Workshop review |


[Breakout Group Assignments](https://docs.google.com/spreadsheets/d/1M4jT2TDf3G9TPejg3Rkdnpr1_1PoMpL1/edit?usp=sharing&ouid=100082783551785338508&rtpof=true&sd=true)


## Pre-workshop preparations (15 minutes) {.unnumbered}

The workshop will be run via Zoom, and we will be using a GoogleDoc for shared note taking and interaction during the sessions.   Breakout sessions and analytical components will be conducted using R.  

For R, there are two options: either have R & RStudio downloaded on your machine, or use a RStudio Cloud project created for this workshop (recommended).  

Why RStudio Cloud? We want to maximize time during our workshop for learning, and not on tech support. Using a standard way of interacting with the course material makes this easier, and avoids the hassles of multiple installation types, versions of R, etc. However, you may wish to set up R and RStudio on your local machine, so information about required packages will be posted below.  


### RStudio Cloud {.unnumbered}

Before the workshop, please visit [Rstudio Cloud](https://rstudio.cloud) and create a free account.  
Free accounts give limited usage, but are more than enough for these workshops.  

Instructions for how to navigate to our RStudio Cloud project and set up the project so you can work on the exercises in your own web browser can be found here.
[RStudio Cloud set up guide & instructions](https://github.com/gavinfay/asmfc-mse/issues/1)


### R & RStudio on own machine {.unnumbered}

**Download and install R and RStudio**
- R: <https://cloud.r-project.org/>
- RStudio: <http://www.rstudio.com/download>
- Follow your operating system's normal installation process

**Getting the workshop materials to your computer**
You can create a R Studio project from the github repository for the workshop.  
[RStudio project set up guide](https://github.com/gavinfay/asmfc-mse/issues/2)

**R Packages used**
If not using the RStudio Cloud project, we will be using the following R packages and you can install them on your local machine ahead of time by running the below code in the R console (copy & paste).  

```{r eval=FALSE}
pkgs_to_use <- c("tidyverse",
                 "palmerpenguins",
                 "furrr",
                 "MASS",
                 "janitor",
                 "skimr",
                 "Hmisc",
                 "mvtnorm",
                 "bookdown")
install.packages(setdiff(pkgs_to_use, rownames(installed.packages())))  
```


## Code of Conduct {.unnumbered}

These workshops follow the [Fay Lab code of conduct:](https://thefaylab.github.io/lab-manual/code)


## Licensing {.unnumbered}

All materials are released with [Creative Commons Attribution Share Alike 4.0 International](LICENSE.md) license.


This website is built with [bookdown](https://bookdown.org/), the lovely icons by [icons8](http://icons8.com/).  


<!-- 1. **Download workshop data**  -->
<!--     - Google Drive folder: [r-for-excel-data ](https://drive.google.com/drive/folders/1RywSUw8hxETlROdIhLIntxPsZq0tKSdS?usp=sharing) -->
<!--     - Save it temporarily somewhere you will remember; we will move it together -->
    
<!---
1. Get comfortable: if you're not in a physical workshop, be set up with two screens if possible. You will be following along in RStudio on your own computer while also watching a virtual training or following this tutorial on your own.
--->

<!-- ## Data citations -->

<!-- We use the following data from the Santa Barbara Coastal Term Ecological Research and National  Oceanic and Atmospheric Administration in this workshop:  -->

<!-- - **fish.csv** -->
<!--   - Description: Reef fish abundance, SB coast -->
<!--   - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=17&revision=newest -->
<!--   - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Fish abundance. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/dbd1d5f0b225d903371ce89b09ee7379). -->
<!-- - **inverts.xlsx** -->
<!--   - Description: Invertebrate counts, SB coast -->
<!--   - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=19&revision=newest -->
<!--   - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Invertebrate and algal density. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/748ee568669ca2b740e9b8f5f8a085d8).  -->
<!-- - **kelp.xlsx** -->
<!--   - Description: Giant kelp abundance and size, SB coast -->
<!--   - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=18&revision=newest                         -->
<!--   - Citation: Reed D. 2018. SBC LTER: Reef: Kelp Forest Community Dynamics: Abundance and size of Giant Kelp (Macrocystis Pyrifera), ongoing since 2000. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/dea56e02127161194626f97c8b6118e8).  -->
<!-- - **lobsters.xlsx and lobsters2.xlsx** -->
<!--   - Description: Lobster size, abundance and fishing pressure (SB coast) -->
<!--   - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=77&revision=newest -->
<!--   - Citation: Reed D. 2019. SBC LTER: Reef: Abundance, size and fishing effort for California Spiny Lobster (Panulirus interruptus), ongoing since 2012. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/a593a675d644fdefb736750b291579a0).  -->
<!-- - **noaa_fisheries.csv** -->
<!--   - Description: NOAA Commercial Fisheries Landing data (1950 - 2017) -->
<!--   - Link: https://www.st.nmfs.noaa.gov/commercial-fisheries/commercial-landings/ -->
<!--   - Source: Fisheries Statistics Division of the NOAA Fisheries -->
<!-- - **substrate.xlsx ** -->
<!--   - Description: Algal cover, invertebrates and substrates near Santa Cruz Island -->
<!--   - Link: https://portal.edirepository.org/nis/mapbrowse?scope=knb-lter-sbc&identifier=38&revision=newest -->
<!--   - Citation: Schmitt R. J., S. J. Holbrook. 2012. SBC LTER: Santa Cruz Island: Cover of Algae, Invertebrates and Benthic Substrate. Environmental Data Initiative. [doi](https://doi.org/10.6073/pasta/9ce22c5b70d3e6ef8f0445e6cf782f87).  -->
<!-- - **ca_np.csv and ci_np.xlsx** -->
<!--   - Description: US National Parks visitation data (1904 - 2016) -->
<!--   - Link: https://data.world/inform8n/us-national-parks-visitation-1904-2016-with-boundaries -->
<!--   - Source: Data originally accessed from the US Department of the Interior National Park Service’s Integrated Resource Management Applications data portal (https://irma.nps.gov/) -->
